apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - backend:
          serviceName: clusterip
          servicePort: 1234
