apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: webapplication1
  ports:
    - port: 3355 # kubernetes port
      targetPort: 80 # pod port
  type: LoadBalancer
